version: '3.8'
services:
  db:
    image: postgressql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: orders
    volumes:
      - ./data:/var/lib/postgresql/data
